package fr.ubo.fast.common.constant;

public enum DatabaseSchemaProperties
{
	RAW_TIME_SERIES_DATA_TABLE(Constants.RAW_TIME_SERIES_DATA_TABLE),
	RAW_TIME_SERIES_DATA_TIME_COLUMN(Constants.RAW_TIME_SERIES_DATA_TIME_COLUMN),
	RAW_TIME_SERIES_DATA_VALUE_COLUMN(Constants.RAW_TIME_SERIES_DATA_VALUE_COLUMN),
	RAW_TIME_SERIES_DATA_QUALITY_COLUMN(Constants.RAW_TIME_SERIES_DATA_QUALITY_COLUMN),
	RAW_TIME_SERIES_DATA_TIME_SERIES_ID_COLUMN(Constants.RAW_TIME_SERIES_DATA_TIME_SERIES_ID_COLUMN),
	AGGREGATED_TIME_SERIES_DATA_TABLE_PATTERN(Constants.AGGREGATED_TIME_SERIES_DATA_TABLE_PATTERN),
	AGGREGATED_TIME_SERIES_DATA_TIME_COLUMN(Constants.AGGREGATED_TIME_SERIES_DATA_TIME_COLUMN),
	AGGREGATED_TIME_SERIES_DATA_MIN_COLUMN(Constants.AGGREGATED_TIME_SERIES_DATA_MIN_COLUMN),
	AGGREGATED_TIME_SERIES_DATA_MAX_COLUMN(Constants.AGGREGATED_TIME_SERIES_DATA_MAX_COLUMN),
	AGGREGATED_TIME_SERIES_DATA_AVERAGE_COLUMN(Constants.AGGREGATED_TIME_SERIES_DATA_AVERAGE_COLUMN),
	AGGREGATED_TIME_SERIES_DATA_MEDIAN_COLUMN(Constants.AGGREGATED_TIME_SERIES_DATA_MEDIAN_COLUMN),
	AGGREGATED_TIME_SERIES_DATA_FIRST_QUARTILE_COLUMN(Constants.AGGREGATED_TIME_SERIES_DATA_FIRST_QUARTILE_COLUMN),
	AGGREGATED_TIME_SERIES_DATA_LAST_QUARTILE_COLUMN(Constants.AGGREGATED_TIME_SERIES_DATA_LAST_QUARTILE_COLUMN),
	AGGREGATED_TIME_SERIES_DATA_VALUES_NUMBER_COLUMN(Constants.AGGREGATED_TIME_SERIES_DATA_VALUES_NUMBER_COLUMN),
	AGGREGATED_TIME_SERIES_DATA_MIN_QUALITY_COLUMN(Constants.AGGREGATED_TIME_SERIES_DATA_MIN_QUALITY_COLUMN),
	AGGREGATED_TIME_SERIES_DATA_MAX_QUALITY_COLUMN(Constants.AGGREGATED_TIME_SERIES_DATA_MAX_QUALITY_COLUMN),
	CONFIGURATIONS_TABLE(Constants.CONFIGURATIONS_TABLE),
	CONFIGURATIONS_TIME_SERIES_ID_COLUMN(Constants.CONFIGURATIONS_TIME_SERIES_ID_COLUMN),
	CONFIGURATIONS_AGGREGATION_TYPE_COLUMN(Constants.CONFIGURATIONS_AGGREGATION_TYPE_COLUMN),
	CONFIGURATIONS_INTERVAL_COLUMN(Constants.CONFIGURATIONS_INTERVAL_COLUMN),
	CONFIGURATIONS_AGGREGATION_TABLE_COLUMN(Constants.CONFIGURATIONS_AGGREGATION_TABLE_COLUMN),
	TIME_SERIES_META_DATA_TABLE(Constants.TIME_SERIES_META_DATA_TABLE),
	TIME_SERIES_META_DATA_ID_COLUMN(Constants.TIME_SERIES_META_DATA_ID_COLUMN),
	TIME_SERIES_META_DATA_START_DATE_COLUMN(Constants.TIME_SERIES_META_DATA_START_DATE_COLUMN),
	TIME_SERIES_META_DATA_END_DATE_COLUMN(Constants.TIME_SERIES_META_DATA_END_DATE_COLUMN),
	TIME_SERIES_META_DATA_PERIOD_COLUMN(Constants.TIME_SERIES_META_DATA_PERIOD_COLUMN),
	TIME_SERIES_META_DATA_MIN_QUALITY_COLUMN(Constants.TIME_SERIES_META_DATA_MIN_QUALITY_COLUMN),
	TIME_SERIES_META_DATA_MAX_QUALITY_COLUMN(Constants.TIME_SERIES_META_DATA_MAX_QUALITY_COLUMN),
	TIME_SERIES_META_DATA_MEASURED_VARIABLE_ID(Constants.TIME_SERIES_META_DATA_MEASURED_VARIABLE_ID),
	MEASURED_VARIABLES_META_DATA_TABLE(Constants.MEASURED_VARIABLES_META_DATA_TABLE),
	MEASURED_VARIABLES_META_DATA_ID_COLUMN(Constants.MEASURED_VARIABLES_META_DATA_ID_COLUMN),
	MEASURED_VARIABLES_META_DATA_NAME_COLUMN(Constants.MEASURED_VARIABLES_META_DATA_NAME_COLUMN),
	MEASURED_VARIABLES_META_DATA_UNIT_COLUMN(Constants.MEASURED_VARIABLES_META_DATA_UNIT_COLUMN),
	USER_PROFILES_TABLE(Constants.USER_PROFILES_TABLE),
	USER_PROFILES_ID_COLUMN(Constants.USER_PROFILES_ID_COLUMN),
	USER_PROFILE_ENTRIES_TABLE(Constants.USER_PROFILE_ENTRIES_TABLE),
	USER_PROFILE_ENTRIES_ID_COLUMN(Constants.USER_PROFILE_ENTRIES_ID_COLUMN),
	USER_PROFILE_ENTRIES_USER_ID_COLUMN(Constants.USER_PROFILE_ENTRIES_USER_ID_COLUMN),
	USER_PROFILE_ENTRIES_TIME_SERIES_ID_COLUMN(Constants.USER_PROFILE_ENTRIES_TIME_SERIES_ID_COLUMN),
	USER_PROFILE_ENTRIES_START_DATE_COLUMN(Constants.USER_PROFILE_ENTRIES_START_DATE_COLUMN),
	USER_PROFILE_ENTRIES_END_DATE_COLUMN(Constants.USER_PROFILE_ENTRIES_END_DATE_COLUMN),
	USER_PROFILE_ENTRIES_AGGREGATION_TYPE_COLUMN(Constants.USER_PROFILE_ENTRIES_AGGREGATION_TYPE_COLUMN),
	USER_PROFILE_ENTRIES_ZOOM_INTERVAL_COLUMN(Constants.USER_PROFILE_ENTRIES_ZOOM_INTERVAL_COLUMN),
	USER_PROFILE_ENTRIES_VALUES_NUMBER_COLUMN(Constants.USER_PROFILE_ENTRIES_VALUES_NUMBER_COLUMN);

	private final String text;
	
	DatabaseSchemaProperties(final String text)
	{
		this.text = text;
	}
	
	@Override
	public String toString()
	{
		return text;
	}
	
	// To be able to use enumeration values in annotations
	public static class Constants
	{
		public static final String RAW_TIME_SERIES_DATA_TABLE = "observations";
		public static final String RAW_TIME_SERIES_DATA_TIME_COLUMN = "time";
		public static final String RAW_TIME_SERIES_DATA_VALUE_COLUMN = "value";
		public static final String RAW_TIME_SERIES_DATA_QUALITY_COLUMN = "quality";
		public static final String RAW_TIME_SERIES_DATA_TIME_SERIES_ID_COLUMN = "time_series_id";
		public static final String AGGREGATED_TIME_SERIES_DATA_TABLE_PATTERN = "observations_id_%s_interval_%s";
		public static final String AGGREGATED_TIME_SERIES_DATA_TIME_COLUMN = "time_interval";
		public static final String AGGREGATED_TIME_SERIES_DATA_MIN_COLUMN = "min_aggregate";
		public static final String AGGREGATED_TIME_SERIES_DATA_MAX_COLUMN = "max_aggregate";
		public static final String AGGREGATED_TIME_SERIES_DATA_AVERAGE_COLUMN = "average_aggregate";
		public static final String AGGREGATED_TIME_SERIES_DATA_MEDIAN_COLUMN = "median_aggregate";
		public static final String AGGREGATED_TIME_SERIES_DATA_FIRST_QUARTILE_COLUMN = "first_quartile_aggregate";
		public static final String AGGREGATED_TIME_SERIES_DATA_LAST_QUARTILE_COLUMN = "last_quartile_aggregate";
		public static final String AGGREGATED_TIME_SERIES_DATA_VALUES_NUMBER_COLUMN = "values_number";
		public static final String AGGREGATED_TIME_SERIES_DATA_MIN_QUALITY_COLUMN = "min_quality";
		public static final String AGGREGATED_TIME_SERIES_DATA_MAX_QUALITY_COLUMN = "max_quality";
		public static final String TIME_SERIES_META_DATA_MEASURED_VARIABLE_ID = "measured_variable_id";
		public static final String CONFIGURATIONS_TABLE = "configurations";
		public static final String CONFIGURATIONS_TIME_SERIES_ID_COLUMN = "time_series_id";
		public static final String CONFIGURATIONS_AGGREGATION_TYPE_COLUMN = "aggregation_type";
		public static final String CONFIGURATIONS_INTERVAL_COLUMN = "interval";
		public static final String CONFIGURATIONS_AGGREGATION_TABLE_COLUMN = "aggregation_table";
		public static final String TIME_SERIES_META_DATA_TABLE = "time_series";
		public static final String TIME_SERIES_META_DATA_ID_COLUMN = "time_series_id";
		public static final String TIME_SERIES_META_DATA_START_DATE_COLUMN = "start_date";
		public static final String TIME_SERIES_META_DATA_END_DATE_COLUMN = "end_date";
		public static final String TIME_SERIES_META_DATA_PERIOD_COLUMN = "period";
		public static final String TIME_SERIES_META_DATA_MIN_QUALITY_COLUMN = "min_quality";
		public static final String TIME_SERIES_META_DATA_MAX_QUALITY_COLUMN = "max_quality";
		public static final String MEASURED_VARIABLES_META_DATA_TABLE = "measured_variables";
		public static final String MEASURED_VARIABLES_META_DATA_ID_COLUMN = "measured_variable_id";
		public static final String MEASURED_VARIABLES_META_DATA_NAME_COLUMN = "name";
		public static final String MEASURED_VARIABLES_META_DATA_UNIT_COLUMN = "unit";
		public static final String USER_PROFILES_TABLE = "user_profiles";
		public static final String USER_PROFILES_ID_COLUMN = "user_id";
		public static final String USER_PROFILE_ENTRIES_TABLE = "user_profile_entries";
		public static final String USER_PROFILE_ENTRIES_ID_COLUMN = "user_profile_entry_id";
		public static final String USER_PROFILE_ENTRIES_USER_ID_COLUMN = "user_id";
		public static final String USER_PROFILE_ENTRIES_TIME_SERIES_ID_COLUMN = "time_series_id";
		public static final String USER_PROFILE_ENTRIES_START_DATE_COLUMN = "start_date";
		public static final String USER_PROFILE_ENTRIES_END_DATE_COLUMN = "end_date";
		public static final String USER_PROFILE_ENTRIES_AGGREGATION_TYPE_COLUMN = "aggregation_type";
		public static final String USER_PROFILE_ENTRIES_ZOOM_INTERVAL_COLUMN = "zoom_interval";
		public static final String USER_PROFILE_ENTRIES_VALUES_NUMBER_COLUMN = "values_number";	
	}
}