/*
 * generated by Xtext 2.14.0
 */
package fr.ubo.fast.dsl.tests

import com.google.inject.Inject
import fr.ubo.fast.TimeSeriesFramework
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(DslInjectorProvider)
class DslParsingTest
{
	@Inject
	ParseHelper<TimeSeriesFramework> parseHelper
	
	@Test
	def void loadModel()
	{
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
		val errors = result.eResource.errors
		Assert.assertTrue('''Unexpected errors: «errors.join(", ")»''', errors.isEmpty)
	}
}
