/**
 * generated by Xtext 2.14.0
 */
package fr.ubo.fast.dsl.ide;

import fr.ubo.fast.dsl.ide.AbstractDslIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class DslIdeModule extends AbstractDslIdeModule {
}
