version: "2"
services:
  timescaledb:
    container_name: "${TIME_SCALE_DB_CONTAINER_NAME}"
    build:
      context: "./time_scale_db"
      dockerfile: "docker_file"
    env_file:
      - "./time_scale_db/environment.env"
    volumes:
      - "./time_scale_db/data:/data"
      - "${DATA_DIRECTORY}:/var/lib/postgresql/data"
    ports:
      - "${TIME_SCALE_DB_PORT}:5432"
    networks:
      - local_network
    restart: on-failure
    # healthcheck:
    #   test: /usr/bin/pg_isready -U postgres
    #   interval: 5s
    #   timeout: 10s
    #   retries: 120
    # mem_limit: 6G
    # mem_reservation: 4G
    # cpuset: 0-1
  apache:
    container_name: "${WEB_SERVER_CONTAINER_NAME}"
    image: "tomcat:9.0.70-jre8"
    volumes:
      - "./apache/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml:rw"
      - "./apache/fr.ubo.fast.data.manager-0.0.1-SNAPSHOT.war:/usr/local/tomcat/webapps/fr.ubo.fast.data.manager-0.0.1-SNAPSHOT.war"
    ports:
      - "${WEB_SERVER_PORT}:8080"
    networks:
      - local_network
    restart: on-failure
networks:
  local_network: