/*
 * generated by Xtext 2.14.0
 */
package fr.ubo.fast.dsl.ui.tests;

import com.google.inject.Injector;
import fr.ubo.fast.dsl.ui.internal.DslActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class DslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DslActivator.getInstance().getInjector("fr.ubo.fast.dsl.Dsl");
	}

}
